-- This migration was generated as a duplicate full init after prior
-- migrations already created the schema. Keep it as a no-op so fresh
-- databases can apply the ordered migration history safely.
